version: "3.7"
services:
  app:
    image: drivedemon/php-node-composer-xdebug:latest
    container_name: app
    working_dir: /var/www/
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravel-simple
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    volumes:
      - ./.docker/db_app_v3_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./.docker/config/nginx:/etc/nginx/conf.d

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
