version: '3.7'
services:
    web:
      image: laravel-loan
      ports:
        - 8000:8000
      environment:
        MYSQL_DATABASE: laravel-loan
        MYSQL_USER: admin
        MYSQL_PASSWORD: 1234
        MYSQL_HOST: db-laravel-loan
      volumes:
        - ./:/app
      depends_on:
        - db

    db:
      container_name: db-laravel-loan
      platform: linux/x86_64
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3306:3306
      restart: always
      volumes:
        - ./mysqldata:/var/lib/mysql:cached
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravel-loan
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=1234
